"""
Base strategy ABC and TradeSignal dataclass.
All strategies inherit from BaseStrategy.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field


@dataclass
class TradeSignal:
    """A trading signal generated by a strategy."""
    strategy: str
    ticker: str
    side: str  # "buy" or "sell"
    direction: str  # "long" or "short"
    shares: float = 0.0
    price: float = 0.0
    stop_price: float | None = None
    target_price: float | None = None
    strength: float = 0.0  # 0-1, used for priority ranking
    reason: str = ""
    details: dict = field(default_factory=dict)


@dataclass
class ExitSignal:
    """An exit signal for an existing position."""
    position_id: int
    ticker: str
    reason: str
    current_price: float = 0.0
    new_stop: float | None = None  # If set, update stop instead of exiting


class BaseStrategy(ABC):
    """Abstract base class for all competition strategies."""

    name: str = "base"

    @abstractmethod
    def generate_signals(self, market_data: dict) -> list[TradeSignal]:
        """
        Analyze market data and generate entry signals.
        market_data contains DataFrames keyed by timeframe.
        Returns list of TradeSignal objects.
        """
        ...

    @abstractmethod
    def check_exits(self, positions: list[dict], market_data: dict) -> list[ExitSignal]:
        """
        Check open positions for exit conditions.
        Returns list of ExitSignal objects.
        """
        ...
